- name: Deploy container
  hosts: all
  tasks:
    - name: Run Deploy script
      ansible.builtin.script: ./ansible-deploy-container.sh
      environment:
        DOCKERIO_USERNAME: "{{ dockerio_username }}"
