- name: Deploy Docker container
  hosts: all
  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ DOCKERIO_USERNAME }}/hello-go"
        tag: latest
        source: pull

    - name: Stop existing container (if running)
      community.docker.docker_container:
        name: hello-go
        state: stopped
      ignore_errors: yes

    - name: Remove existing container (if it exists)
      community.docker.docker_container:
        name: hello-go
        state: absent
      ignore_errors: yes

    - name: Run new Docker container
      community.docker.docker_container:
        name: hello-go
        image: "{{ DOCKERIO_USERNAME }}/hello-go:latest"
        state: started
        restart_policy: unless-stopped
        ports:
          - "3000:8080"
