name: Publish Docker image

on:
  push:
    branches:
      # - main
      - none

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t docker.io/${{secrets.DOCKER_USERNAME}}/hello-go:latest .

      - name: Push the Docker image
        run: |
          docker push docker.io/${{secrets.DOCKER_USERNAME}}/hello-go:latest
