name: Deploy Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t docker.io/${{secrets.DOCKER_USERNAME}}/hello-go:latest .

      - name: Push the Docker image
        run: |
          docker push docker.io/${{secrets.DOCKER_USERNAME}}/hello-go:latest

  deploy_to_server:
    name: Pull Docker image and restart
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          use-cache: "true"

      - name: Wait for Tailscale to be ready
        run: sleep 5

      - name: Run timestamp playbook
        run: |
          cd .ansible 
          ansible-playbook -i ${{ secrets.TS_TARGET_HOSTNAME }}, timestamp.yml -u ${{ secrets.TARGET_USERNAME }} -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"
          cd -

      - name: Run docker deploy playbook
        run: |
          cd .ansible 
          ansible-playbook -i ${{ secrets.TS_TARGET_HOSTNAME }}, deploy-container.yml -u ${{ secrets.TARGET_USERNAME }} -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no'" --extra-vars "dockerio_username=${{secrets.DOCKER_USERNAME}}"
          cd -
