name: Hello Tailscale SSH

on:
  workflow_dispatch:

jobs:
  hello-tailscale:
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          use-cache: "true"

      - name: Wait for Tailscale to be ready
        run: sleep 5

      - name: Run remote command via Tailscale SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TARGET_USERNAME }}@${{ secrets.TS_TARGET_HOSTNAME }} \
            'echo "Hello from GitHub Actions via Tailscale SSH" > ~/tssh.txt'
