name: SSH over taiscale

on:
  workflow_dispatch:

jobs:
  ssh-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey ${{ secrets.TS_AUTHKEY }} --hostname github-runner --ephemeral

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH and touch hello.txt
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@<target-tailnet-IP-or-hostname> 'touch ~/hello.txt && echo "✅ Hello from GH Actions!"'
